/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PurchasesRouteImport } from './routes/purchases'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MembersRouteImport } from './routes/members'
import { Route as ItemsRouteImport } from './routes/items'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as DirectoryRouteImport } from './routes/directory'
import { Route as BillsRouteImport } from './routes/bills'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ItemsIdRouteImport } from './routes/items.$id'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as BusinessSettingsRouteImport } from './routes/business.settings'
import { Route as BusinessNewRouteImport } from './routes/business.new'
import { Route as BillsIdRouteImport } from './routes/bills.$id'

const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesRoute = PurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsRoute = ItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsRoute = BillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsIdRoute = ItemsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ItemsRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessSettingsRoute = BusinessSettingsRouteImport.update({
  id: '/business/settings',
  path: '/business/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessNewRoute = BusinessNewRouteImport.update({
  id: '/business/new',
  path: '/business/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsIdRoute = BillsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BillsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bills': typeof BillsRouteWithChildren
  '/directory': typeof DirectoryRoute
  '/expenses': typeof ExpensesRoute
  '/items': typeof ItemsRouteWithChildren
  '/members': typeof MembersRoute
  '/onboarding': typeof OnboardingRoute
  '/purchases': typeof PurchasesRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sales': typeof SalesRoute
  '/bills/$id': typeof BillsIdRoute
  '/business/new': typeof BusinessNewRoute
  '/business/settings': typeof BusinessSettingsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/items/$id': typeof ItemsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bills': typeof BillsRouteWithChildren
  '/directory': typeof DirectoryRoute
  '/expenses': typeof ExpensesRoute
  '/items': typeof ItemsRouteWithChildren
  '/members': typeof MembersRoute
  '/onboarding': typeof OnboardingRoute
  '/purchases': typeof PurchasesRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sales': typeof SalesRoute
  '/bills/$id': typeof BillsIdRoute
  '/business/new': typeof BusinessNewRoute
  '/business/settings': typeof BusinessSettingsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/items/$id': typeof ItemsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bills': typeof BillsRouteWithChildren
  '/directory': typeof DirectoryRoute
  '/expenses': typeof ExpensesRoute
  '/items': typeof ItemsRouteWithChildren
  '/members': typeof MembersRoute
  '/onboarding': typeof OnboardingRoute
  '/purchases': typeof PurchasesRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sales': typeof SalesRoute
  '/bills/$id': typeof BillsIdRoute
  '/business/new': typeof BusinessNewRoute
  '/business/settings': typeof BusinessSettingsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/items/$id': typeof ItemsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bills'
    | '/directory'
    | '/expenses'
    | '/items'
    | '/members'
    | '/onboarding'
    | '/purchases'
    | '/reports'
    | '/reset-password'
    | '/sales'
    | '/bills/$id'
    | '/business/new'
    | '/business/settings'
    | '/invite/$token'
    | '/items/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bills'
    | '/directory'
    | '/expenses'
    | '/items'
    | '/members'
    | '/onboarding'
    | '/purchases'
    | '/reports'
    | '/reset-password'
    | '/sales'
    | '/bills/$id'
    | '/business/new'
    | '/business/settings'
    | '/invite/$token'
    | '/items/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/bills'
    | '/directory'
    | '/expenses'
    | '/items'
    | '/members'
    | '/onboarding'
    | '/purchases'
    | '/reports'
    | '/reset-password'
    | '/sales'
    | '/bills/$id'
    | '/business/new'
    | '/business/settings'
    | '/invite/$token'
    | '/items/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BillsRoute: typeof BillsRouteWithChildren
  DirectoryRoute: typeof DirectoryRoute
  ExpensesRoute: typeof ExpensesRoute
  ItemsRoute: typeof ItemsRouteWithChildren
  MembersRoute: typeof MembersRoute
  OnboardingRoute: typeof OnboardingRoute
  PurchasesRoute: typeof PurchasesRoute
  ReportsRoute: typeof ReportsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SalesRoute: typeof SalesRoute
  BusinessNewRoute: typeof BusinessNewRoute
  BusinessSettingsRoute: typeof BusinessSettingsRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases': {
      id: '/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof PurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items': {
      id: '/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills': {
      id: '/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof BillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/$id': {
      id: '/items/$id'
      path: '/$id'
      fullPath: '/items/$id'
      preLoaderRoute: typeof ItemsIdRouteImport
      parentRoute: typeof ItemsRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/settings': {
      id: '/business/settings'
      path: '/business/settings'
      fullPath: '/business/settings'
      preLoaderRoute: typeof BusinessSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/new': {
      id: '/business/new'
      path: '/business/new'
      fullPath: '/business/new'
      preLoaderRoute: typeof BusinessNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills/$id': {
      id: '/bills/$id'
      path: '/$id'
      fullPath: '/bills/$id'
      preLoaderRoute: typeof BillsIdRouteImport
      parentRoute: typeof BillsRoute
    }
  }
}

interface BillsRouteChildren {
  BillsIdRoute: typeof BillsIdRoute
}

const BillsRouteChildren: BillsRouteChildren = {
  BillsIdRoute: BillsIdRoute,
}

const BillsRouteWithChildren = BillsRoute._addFileChildren(BillsRouteChildren)

interface ItemsRouteChildren {
  ItemsIdRoute: typeof ItemsIdRoute
}

const ItemsRouteChildren: ItemsRouteChildren = {
  ItemsIdRoute: ItemsIdRoute,
}

const ItemsRouteWithChildren = ItemsRoute._addFileChildren(ItemsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BillsRoute: BillsRouteWithChildren,
  DirectoryRoute: DirectoryRoute,
  ExpensesRoute: ExpensesRoute,
  ItemsRoute: ItemsRouteWithChildren,
  MembersRoute: MembersRoute,
  OnboardingRoute: OnboardingRoute,
  PurchasesRoute: PurchasesRoute,
  ReportsRoute: ReportsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SalesRoute: SalesRoute,
  BusinessNewRoute: BusinessNewRoute,
  BusinessSettingsRoute: BusinessSettingsRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
